protected/models/Feed.php
<?php

/**
 * This is the model class for table "tbl_feed".
 *
 * The followings are the available columns in table 'tbl_feed':
 * @property integer $id
 * @property string $name
 * @property string $link
 * @property string $img_link
 * @property string $description
 * @property integer $user_id
 */
class Feed extends CActiveRecord
{
	/**
	 * Returns the static model of the specified AR class.
	 * @param string $className active record class name.
	 * @return Pin the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'tbl_feed';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('name, link, original_img_link, thumb_img_link, mid_img_link, user_id, category_id', 'required'),
			array('user_id', 'numerical', 'integerOnly'=>true),
			array('name, link, original_img_link, thumb_img_link, mid_img_link', 'length', 'max'=>100),
			array('description', 'length', 'max'=>1000),
			// The following rule is used by search().
			// Please remove those attributes that should not be searched.
			array('id, name, link, original_img_link, thumb_img_link, mid_img_link, description, user_id, user_name', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
			'user'=>array(self::BELONGS_TO, 'User', 'user_id'),
			'category'=>array(self::BELONGS_TO, 'FeedCategory', 'category_id'),
			'subscribe'=>array(self::HAS_MANY, 'Subscribe', 'feed_id'),
			'subCount' => array(self::STAT, 'Subscribe', 'feed_id'),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'ID',
			'name' => '名称',
			'link' => '地址',
			'thumb_img_link' => '缩略图图片',
			'mid_img_link' => '中等尺寸图片',
			'original_img_link' => '原尺寸图片',
			'description' => '描述',
			'user_id' => '用户',
			'category_id' => '目录',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 * @return CActiveDataProvider the data provider that can return the models based on the search/filter conditions.
	 */
	public function search()
	{
		// Warning: Please modify the following code to remove attributes that
		// should not be searched.

		$criteria=new CDbCriteria;
		
		$criteria->compare('t.id',$this->id);
		$criteria->compare('t.name',$this->name,true);
		$criteria->compare('t.link',$this->link,true);
		$criteria->compare('t.description',$this->description,true);
		$criteria->compare('t.user_id',$this->user_id);
		$criteria->compare('t.category_id',$this->category_id);
		
		//$criteria->compare('subscribe.user_id',1);
		
		if (isset(Yii::app()->user->id))
		{
			$userCondition = 'subscribe.user_id=';
			$userCondition .= Yii::app()->user->id;
			$criteria->with=array(
					'user',
					'category',
					'subscribe'=>array('condition'=>$userCondition),
				);
		}
		else
		{
			$criteria->with=array(
					'user',
					'category',
					);
		}
		
		//$Criteria->join = 'LEFT JOIN tpl_subscribe ON tpl_subscribe.pin_id = t.id';
		return new CActiveDataProvider( $this, array(
			'criteria'=>$criteria,
			'sort'=>array(
				'attributes'=>array(
					'user_name'=>array(
						'asc'=>'user.username',
						'desc'=>'user.username DESC',
					),
					'*',
				),
			),
			'pagination'=>array(
				'pageSize'=>20,
			),
		));
	}

	public static function GetPinWithSubStatus($sub_user_id)
	{
		$criteria = new CDbCriteria();
	 
		$pins = Pin::model()->findAll($criteria);

		foreach($pins as $pin)
		{
			Pin::model()->getSubStatus($sub_user_id, $pin->id);
			$pin->is_subed_by_user = true;
			$pin->$subscribe_id = 0;
		}
		
		return $pins;
	}
	
	public function load($userID = NULL, $catID = null, $orderBy = null)
	{
		$criteria=new CDbCriteria;
		$sub_table = Subscribe::model()->tableName();
		$sub_count_sql = "(select count(*) from $sub_table pt where pt.feed_id = t.id)";
 
		// select
		$criteria->with=array(
					'subCount',
					);
	
		if ($catID != null)
		{
			$criteria->compare('t.category_id',$catID);
		}
		if ($userID != null)
		{
			$criteria->compare('t.user_id',Yii::app()->user->id);
		}
		
		if ($orderBy == 'id')
		{
			$criteria->order="t.id DESC";
		}
		else if ($orderBy == 'random')
		{
			$criteria->order="RAND()";
		}
		else if ($orderBy == 'subCount')
		{
			$criteria->order=$sub_count_sql . "DESC";
		}
		
		return new CActiveDataProvider('Feed',array(
			'criteria'=>$criteria,
		));
	}
}

	

protected/controllers/FeedController.php
<?php

class FeedController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	public $sortMenu = null;
	public $category = null;
	
	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'explore' and 'view' actions
				'actions'=>array('view', 'index', 'random'),
				'users'=>array('*'),
			),
			array('allow', // allow authenticated user to perform 'create' 'index' and 'update' actions
				'actions'=>array('create','update', 'home'),
				'users'=>array('@'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('admin','delete'),
				'users'=>array('admin'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Feed;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Feed']))
		{
			$model->attributes=$_POST['Feed'];
			$model->user_id=Yii::app()->user->id;
			if($model->save())
				$this->redirect(array('home'));
		}

		$feedCategory = new FeedCategory;
		$categoryProvider=$feedCategory->load();
		
		$this->render('create',array(
			'model'=>$model,
			'dataProvider'=>$categoryProvider,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Feed']))
		{
			$model->attributes=$_POST['Feed'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$feedCategory = new FeedCategory;
		$categoryProvider=$feedCategory->load();
		
		$this->render('update',array(
			'model'=>$model,
			'dataProvider'=>$categoryProvider,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		if(Yii::app()->request->isPostRequest)
		{
			// we only allow deletion via POST request
			$this->loadModel($id)->delete();

			// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
			if(!isset($_GET['ajax']))
				$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('index'));
		}
		else
			throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');
	}

	/**
	 * Lists user's models.
	 */
	public function actionHome($cat = null)
	{
		$feed = new Feed;
		$dataProvider = $feed->load(Yii::app()->user->id, $cat);
		
		$feedCategory = new FeedCategory;
		$categoryProvider=$feedCategory->load();
			
		$this->render('home',array(
			'dataProvider'=>$dataProvider,
			'categoryProvider'=>$categoryProvider,
			'categoryID'=>$cat,
		));
	}
	
	/**
	 * This is the action to 'index'.
	 */
	public function actionIndex($by = null, $cat = null)
	{
		$feed = new Feed;
		if ($by == 0)
			$dataProvider = $feed->load(null, $cat, 'subCount');
		else if ($by == 1)
			$dataProvider = $feed->load(null, $cat, 'id' );
		else if ($by == 2)
			$dataProvider = $feed->load(null, $cat, 'random');
		else
			$dataProvider = $feed->load(null, $cat, 'subCount');
		
		$feedCategory = new FeedCategory;
		$categoryProvider=$feedCategory->load();

		$this->render('index',array(
			'dataProvider'=>$dataProvider,
			'categoryProvider'=>$categoryProvider,
			'sortID'=>$by,
			'categoryID'=>$cat,
		));
	}
	
	/**
	 * Manages all models.
	 */
	 /*
	public function actionAdmin()
	{
		$model=new Feed('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Feed']))
			$model->attributes=$_GET['Feed'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}*/

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer the ID of the model to be loaded
	 */
	public function loadModel($id)
	{
		$model=Feed::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param CModel the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='feed-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

protected/controllers/SubscribeController.php
<?php

class SubscribeController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column1';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('view'),
				'users'=>array('*'),
			),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('update','delete','swap'),
				'users'=>array('@'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($feed_id)
	{
		$model=Subscribe::model()->findByAttributes(array('feed_id'=>$feed_id, 'user_id'=>Yii::app()->user->id));

		if($model==null)
		{
			$model=new Subscribe;
			$model->feed_id = $feed_id;
			$model->user_id = Yii::app()->user->id;
			if($model->save())
			{
				
			}
			else
			{
				throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');
			}
		}
		else
		{
			if ($model->user_id == Yii::app()->user->id)
			{
				$this->loadModel($model->id)->delete();
			}
			else
			{
				throw new CHttpException(403,'Access denied.');
			}
		}
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		if(Yii::app()->request->isPostRequest)
		{
			// we only allow deletion via POST request
			$this->loadModel($id)->delete();
			
			// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
			if(!isset($_GET['ajax']))
			{
				//$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
			}
		}
		else
			throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');
	}

	public function actionSwap()
	{
		if(isset($_POST['srcSubID']) && isset($_POST['dstSubID']))
		{
			$srcSubID = $_POST['srcSubID'];
			$dstSubID = $_POST['dstSubID'];
			$src=SubscribeOrder::model()->findByAttributes(array('subscribe_id'=>$srcSubID));
			$src->delete();
			$dst=SubscribeOrder::model()->findByAttributes(array('subscribe_id'=>$dstSubID));
			$dst->delete();
			
			$newSrc = new SubscribeOrder;
			$newSrc->id = $src->id;
			$newSrc->subscribe_id = $dst->subscribe_id;
			
			$newDst = new SubscribeOrder;
			$newDst->id = $dst->id;
			$newDst->subscribe_id = $src->subscribe_id;
			
			$newSrc->save();
			$newDst->save();
		}
		else
			throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer the ID of the model to be loaded
	 */
	public function loadModel($id)
	{
		$model=Subscribe::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param CModel the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='Subscribe-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

protected/views/feed/_timeline_view.php
<script language="javascript">
function showUnSub(unSubButton)
{
	if (unSubButton.textContent == '已订阅')
	{
		unSubButton.className ='btn btn-danger btn-mini';
		unSubButton.textContent = '取消订阅';
	}
}

function hideUnSub(unSubButton)
{
	if (unSubButton.textContent == '取消订阅')
	{
		unSubButton.className ='btn btn-success btn-mini';
		unSubButton.textContent = '已订阅';
	}
}

function mouseOver(unSubButton, feedButton)
{
	if (!unSubButton)
	{
	}
	else
	{
		unSubButton.style.display='';
	}
}

function mouseOut(unSubButton, feedButton)
{
	if (!unSubButton)
	{
	}
	else
	{
		unSubButton.style.display='none';
	}
}
</script> 

<?php
	$unSubButtonID = 'unSubButton';
	$unSubButtonID .= $data->id;
	$detailButtonID = 'detailButton';
	$detailButtonID .= $data->id;
		
	$showUnSubProc = 'showUnSub(';
	$showUnSubProc .= $unSubButtonID;
	$showUnSubProc .= ')';
	
	$hideUnSubProc = 'hideUnSub(';
	$hideUnSubProc .= $unSubButtonID;
	$hideUnSubProc .= ')';
	
	require('_detail.php');
?>

<li class="span2 feed-pin">
    <div id="feed-thumbnail" class="thumbnail" onMouseOver="mouseOver(<?php echo $unSubButtonID ?>)" onMouseOut="mouseOut(<?php echo $unSubButtonID ?>)">
		<h6 class="feed-name"><?php echo CHtml::encode($data->name); ?></h6>
		<?php 
			$clickFunc = "showFeedModal(";
			$clickFunc .= $data->id;
			$clickFunc .= ",'";
			$clickFunc .= $data->name;
			$clickFunc .= "','";
			$clickFunc .= $data->link;
			$clickFunc .= "','";
			$clickFunc .= $data->mid_img_link;
			$clickFunc .= "','";
			$clickFunc .= $data->category->name;
			$clickFunc .= "','";
			$clickFunc .= $data->description;
			$clickFunc .= "')";
		?>
		<a href="#" rel="tooltip" onClick="<?php echo $clickFunc ?>" data-title="">
			<img class="thumImg" src="<?php echo CHtml::encode($data->thumb_img_link); ?>" alt="" >
		</a>
		<!--p class="feed-category">分类:<?php echo CHtml::encode($data->category->name); ?></p!-->

		<div class="sub-wrapper-bottom-right">	
			<?php if( !Yii::app()->user->isGuest ): ?>
			<?php 	
				if (isset($data->subscribe[0]))
				{
					$buttonLabel = '已订阅';
					$type = 'success';
					$beforeSend = 'js:function(){if(confirm("确定要取消该订阅吗?"))return true;else return false;}';
				}
				else
				{
					$buttonLabel = '订阅';
					$type = 'primary';
					$beforeSend = null;
				}

				$this->widget('bootstrap.widgets.TbButton', array(
									'label'=>$buttonLabel,
									'buttonType'=>'Button',
									'type'=>$type, // null, 'primary', 'info', 'success', 'warning', 'danger' or 'inverse'
									'size'=>'mini',    // null, 'large', 'small' or 'mini'	
									'htmlOptions'=>array(	
											'id' => $unSubButtonID,
											'style' => 'display:none',
											'onMouseOver' => $showUnSubProc,
											'onMouseOut' => $hideUnSubProc,
											'onclick'=>' {'.CHtml::ajax( array(
															   'beforeSend'=>$beforeSend,
															    'type'=>"POST",
																'url' => Yii::app()->createUrl('subscribe/update', array('feed_id'=>$data->id)),
															    'complete' => 'js:function(jqXHR, textStatus) {
																			$.fn.yiiListView.update("feed-thumb");
																			}')
															).'return false;}',
									),
			)); ?>
			<?php endif; ?>
		</div>
    </div>
</li>

protected/views/feed/_view.php
<script language="javascript">
function showUnSub(unSubButton)
{
	if (unSubButton.textContent == '已订阅')
	{
		unSubButton.className ='btn btn-danger btn-mini';
		unSubButton.textContent = '取消订阅';
	}
}

function hideUnSub(unSubButton)
{
	if (unSubButton.textContent == '取消订阅')
	{
		unSubButton.className ='btn btn-success btn-mini';
		unSubButton.textContent = '已订阅';
	}
}

function mouseOver(unSubButton, modifyButton)
{
	if (!unSubButton)
	{
	}
	else
	{
		unSubButton.style.display='';
	}
	if (!modifyButton)
	{
	}
	else
	{
		modifyButton.style.display='';
	}
}

function mouseOut(unSubButton, modifyButton)
{
	if (!unSubButton)
	{
	}
	else
	{
		unSubButton.style.display='none';
	}
	if (!modifyButton)
	{
	}
	else
	{
		modifyButton.style.display='none';
	}
}
</script> 

<?php
	$unSubButtonID = 'unSubButton';
	$unSubButtonID .= $data->id;
	$modifyButtonID = 'modifyButton';
	$modifyButtonID .= $data->id;
	$detailButtonID = 'detailButton';
	$detailButtonID .= $data->id;
		
	$showUnSubProc = 'showUnSub(';
	$showUnSubProc .= $unSubButtonID;
	$showUnSubProc .= ')';
	
	$hideUnSubProc = 'hideUnSub(';
	$hideUnSubProc .= $unSubButtonID;
	$hideUnSubProc .= ')';
	
	require('_detail.php');
?>

<li class="span2 feed-pin">
    <div id="feed-thumbnail" class="thumbnail" onMouseOver="mouseOver(<?php echo $unSubButtonID ?>, <?php echo $modifyButtonID ?>)" onMouseOut="mouseOut(<?php echo $unSubButtonID ?>, <?php echo $modifyButtonID ?>)">
		<div id="feed-thumb-header">
			<h6 class="feed-name"><?php echo CHtml::encode($data->name); ?></h6>
			<?php if(Yii::app()->user->id == $data->user_id) { ?>
			<div class="feed-wrapper-close">
				<?php 
					echo CHtml::ajaxLink(
						"×",
						Yii::app()->createUrl('feed/delete', array('id'=>$data->id)),
						array(	
							'type'=>'POST',
							'dataType'=>'json', 
							'data'=>array(),
							'complete'=>'js:function(jqXHR, textStatus){$.fn.yiiListView.update("feed-thumb");}'
						),
						array( 
							'class' => 'close',
							//'style' => 'display:none',
						)
					);
				?>
				<?php } ?>
			</div>
		</div>
			
		<?php 
			$clickFunc = "showFeedModal(";
			$clickFunc .= $data->id;
			$clickFunc .= ",'";
			$clickFunc .= $data->name;
			$clickFunc .= "','";
			$clickFunc .= $data->link;
			$clickFunc .= "','";
			$clickFunc .= $data->mid_img_link;
			$clickFunc .= "','";
			$clickFunc .= $data->category->name;
			$clickFunc .= "','";
			$clickFunc .= $data->description;
			$clickFunc .= "')";
		?>
		<a href="#" rel="tooltip" onClick="<?php echo $clickFunc ?>" data-title="">
			<img class="thumImg" src="<?php echo CHtml::encode($data->thumb_img_link); ?>" alt="" >
		</a>
		<!--p class="feed-category">分类:<?php echo CHtml::encode($data->category->name); ?></p!-->

		<?php if( !Yii::app()->user->isGuest ){ ?>
		<div class="sub-wrapper-bottom-right">	
			<?php 	
				if (isset($data->subscribe[0]))
				{
					$buttonLabel = '已订阅';
					$type = 'success';
					$beforeSend = 'js:function(){if(confirm("确定要取消该订阅吗?"))return true;else return false;}';
				}
				else
				{
					$buttonLabel = '订阅';
					$type = 'primary';
					$beforeSend = null;
				}
				$this->widget('bootstrap.widgets.TbButton', array(
									'label'=>$buttonLabel,
									'buttonType'=>'Button',
									'type'=>$type, // null, 'primary', 'info', 'success', 'warning', 'danger' or 'inverse'
									'size'=>'mini',    // null, 'large', 'small' or 'mini'	
									'htmlOptions'=>array(	
											'id' => $unSubButtonID,
											'style' => 'display:none',
											'onMouseOver' => $showUnSubProc,
											'onMouseOut' => $hideUnSubProc,
											'onclick'=>' {'.CHtml::ajax( array(
															   'beforeSend'=>$beforeSend,
															    'type'=>"POST",
																'url' => Yii::app()->createUrl('subscribe/update', array('feed_id'=>$data->id)),
															    'complete' => 'js:function(jqXHR, textStatus) {
																			$.fn.yiiListView.update("feed-thumb");
																			}')
															).'return false;}',
									),
			)); ?>
			
			<?php if(Yii::app()->user->id == $data->user_id) { ?>
			<?php $this->widget('bootstrap.widgets.TbButton', array(
									'label'=>'修改',
									'type'=>'warning', // null, 'primary', 'info', 'success', 'warning', 'danger' or 'inverse'
									'size'=>'mini',    // null, 'large', 'small' or 'mini'
									'url' => Yii::app()->createUrl('feed/update', array('id'=>$data->id)),
									'htmlOptions'=>array(	
											'id' => $modifyButtonID,
											'style' => 'display:none',
									),
			)); ?>
			<?php } ?>
	
		</div>
		<?php } ?>
    </div>
</li>

protected/views/feed/create.php
<?php
/*$this->breadcrumbs=array(
	'Pins'=>array('index'),
	'Create',
);*/

$this->menu=array(
	array('label'=>'我的分享','url'=>array('home'),'icon'=>'eye-open'),
	array('label'=>'分享酷站','url'=>array('create'),'icon'=>'icon-plus','active'=>true),
);
?>

<?php echo $this->renderPartial('_form', array('model'=>$model, 'dataProvider'=>$dataProvider)); ?>

protected/views/feed/view.php
<?php
$data=$model;
$this->menu=array(
	array('label'=>'我的分享','url'=>array('home'),'icon'=>'eye-open'),
	array('label'=>'分享酷站','url'=>array('create'),'icon'=>'icon-plus'),
	array('label'=>'查看','url'=>'#','icon'=>'eye-open','active'=>true),
);
?>

<div class="modal-header">
    <h4><?php echo CHtml::encode($data->name); ?></h4>
</div>
 
<div id="feed-detail" class="thumbnail">
		<a href="<?php echo CHtml::encode($data->link); ?>" rel="tooltip" data-title="">
			<img src="<?php echo CHtml::encode($data->mid_img_link); ?>" alt="" >
		</a>

		<p><?php echo CHtml::encode($data->description); ?></p>
		
		<?php if( !Yii::app()->user->isGuest ){ ?>
		<div>
			<?php 	
				if (isset($data->subscribe[0]))
				{
					$buttonLabel = '已订阅';
					$postData = array();
					$url = Yii::app()->createUrl('subscribe/delete', array('id'=>$data->subscribe[0]['id']));
				}
				else
				{
					$buttonLabel = '订阅';
					$postData = array('subscribe'=>array(
													'feed_id'=>$data->id,
													'user_id'=>Yii::app()->user->id,
													)
								);
					$url = Yii::app()->createUrl('subscribe/create');
				}
				$this->widget('bootstrap.widgets.TbButton', array(
									'label'=>$buttonLabel,
									'buttonType'=>'ajaxButton',
									'type'=>'primary', // null, 'primary', 'info', 'success', 'warning', 'danger' or 'inverse'
									'size'=>'mini',    // null, 'large', 'small' or 'mini'
									'url' => $url,		
									'ajaxOptions' => array(
										'type'=>"POST",
										'dataType'=>'json', 
										'data'=>$postData,	
										'complete' => 'js:function(jqXHR, textStatus) {
															$.fn.yiiListView.update("feed-thumb");}',
									),
			)); ?>
			
			<?php if(Yii::app()->user->id == $data->user_id) { ?>
			<?php $this->widget('bootstrap.widgets.TbButton', array(
									'label'=>'删除',
									'buttonType'=>'ajaxButton',
									'type'=>'primary', // null, 'primary', 'info', 'success', 'warning', 'danger' or 'inverse'
									'size'=>'mini',    // null, 'large', 'small' or 'mini'
									'url' => Yii::app()->createUrl('feed/delete', array('id'=>$data->id)),
									'ajaxOptions' => array(
										'type'=>"POST",
										'dataType'=>'json', 					
										'update'=>'#feed-detail'
									),
			)); ?>
			<?php } ?>
	</div>
	<?php } ?>
</div>