protected/controllers/FeedController.php
<?php

class FeedController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	public $sortMenu = null;
	public $category = null;
	
	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'explore' and 'view' actions
				'actions'=>array('view', 'index', 'random'),
				'users'=>array('*'),
			),
			array('allow', // allow authenticated user to perform 'create' 'index' and 'update' actions
				'actions'=>array('create','update', 'home'),
				'users'=>array('@'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('admin','delete'),
				'users'=>array('admin'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Feed;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Feed']))
		{
			$model->attributes=$_POST['Feed'];
			$model->user_id=Yii::app()->user->id;
			if($model->save())
				$this->redirect(array('home'));
		}

		$feedCategory = new FeedCategory;
		$categoryProvider=$feedCategory->load();
		
		$this->render('create',array(
			'model'=>$model,
			'dataProvider'=>$categoryProvider,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Feed']))
		{
			$model->attributes=$_POST['Feed'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$feedCategory = new FeedCategory;
		$categoryProvider=$feedCategory->load();
		
		$this->render('update',array(
			'model'=>$model,
			'dataProvider'=>$categoryProvider,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		if(Yii::app()->request->isPostRequest)
		{
			// we only allow deletion via POST request
			$this->loadModel($id)->delete();

			// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
			if(!isset($_GET['ajax']))
				$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('index'));
		}
		else
			throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');
	}

	/**
	 * Lists user's models.
	 */
	public function actionHome($cat = null)
	{
		$feed = new Feed;
		$dataProvider = $feed->load(Yii::app()->user->id, $cat);
		
		$feedCategory = new FeedCategory;
		$categoryProvider=$feedCategory->load();
			
		$this->render('home',array(
			'dataProvider'=>$dataProvider,
			'categoryProvider'=>$categoryProvider,
			'categoryID'=>$cat,
		));
	}
	
	/**
	 * This is the action to 'index'.
	 */
	public function actionIndex($by = null, $cat = null)
	{
		$feed = new Feed;
		if ($by == 0)
			$dataProvider = $feed->load(null, $cat, 'subCount');
		else if ($by == 1)
			$dataProvider = $feed->load(null, $cat, 'id' );
		else if ($by == 2)
			$dataProvider = $feed->load(null, $cat, 'random');
		else
			$dataProvider = $feed->load(null, $cat, 'subCount');
		
		$feedCategory = new FeedCategory;
		$categoryProvider=$feedCategory->load();

		$this->render('index',array(
			'dataProvider'=>$dataProvider,
			'categoryProvider'=>$categoryProvider,
			'sortID'=>$by,
			'categoryID'=>$cat,
		));
	}
	
	/**
	 * Manages all models.
	 */
	 /*
	public function actionAdmin()
	{
		$model=new Feed('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Feed']))
			$model->attributes=$_GET['Feed'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}*/

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer the ID of the model to be loaded
	 */
	public function loadModel($id)
	{
		$model=Feed::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param CModel the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='feed-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

protected/controllers/SiteController.php
<?php
 
class SiteController extends Controller
{
	public $layout='//layouts/column1';

	/**
	 * Declares class-based actions.
	 */
	public function actions()
	{
		return array(
			// captcha action renders the CAPTCHA image displayed on the contact page
			'captcha'=>array(
				'class'=>'CCaptchaAction',
				'backColor'=>0xFFFFFF,
			),
			// page action renders "static" pages stored under 'protected/views/site/pages'
			// They can be accessed via: index.php?r=site/page&view=FileName
			'page'=>array(
				'class'=>'CViewAction',
			),
		);
	}

	/**
	 * This is the action to handle external exceptions.
	 */
	public function actionError()
	{
		if($error=Yii::app()->errorHandler->error)
		{
			if(Yii::app()->request->isAjaxRequest)
				echo $error['message'];
			else
				$this->render('error', $error);
		}
	}

	/**
	 * Displays the login page
	 */
	public function actionLogin()
	{
		$model=new LoginForm;

		// if it is ajax validation request
		if(isset($_POST['ajax']) && $_POST['ajax']==='login-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}

		// collect user input data
		if(isset($_POST['LoginForm']))
		{
			$model->attributes=$_POST['LoginForm'];
			// validate user input and redirect to the previous page if valid
			if($model->validate() && $model->login())
			{
				$criteria=new CDbCriteria;
				$criteria->compare('t.user_id',Yii::app()->user->id);
				$criteria->order='t.id DESC';
				
				$dataProvider=new CActiveDataProvider('Subscribe',
														array(
															'criteria'=>$criteria,
													));
													
				$this->redirect(Yii::app()->createUrl('/home/'),array(
					'dataProvider'=>$dataProvider,
				));
			}
		}
		// display the login form
		$this->render('login',array('model'=>$model));
	}
	
	/**
	 * Displays the login page
	 */
	public function actionRegister()
	{
		$model=new registerForm;

		// if it is ajax validation request
		if(isset($_POST['ajax']) && $_POST['ajax']==='register-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}

		// collect user input data
		if(isset($_POST['RegisterForm']))
		{
			$model->attributes=$_POST['RegisterForm'];
			// validate user input and redirect to the previous page if valid
			if($model->validate() && $model->register())
			{
				$loginForm=new LoginForm;
				$loginForm->username=$model->username;
				$this->redirect(Yii::app()->createUrl('/site/login'),array(
					'model'=>$loginForm,
				));
			}
		}
		// display the login form
		$this->render('register',array('model'=>$model));
	}

	/**
	 * Logs out the current user and redirect to homepage.
	 */
	public function actionLogout()
	{
		Yii::app()->user->logout();
		$this->redirect(Yii::app()->homeUrl);
	}
}

protected/views/layouts/column1.php
<?php /* @var $this Controller */ ?>
<?php $this->beginContent('//layouts/main'); ?>

<div>
<?php
	$this->widget('bootstrap.widgets.TbMenu', array(
		'type'=>'tabs',
		'stacked'=>false,
		'items'=>$this->menu,
		'htmlOptions'=>array('class'=>'operations'),
	));
?>
</div>

<div id="content">
	<?php echo $content; ?>
</div><!-- content -->
<?php $this->endContent(); ?>

protected/views/layouts/column2.php
<?php /* @var $this Controller */ ?>
<?php $this->beginContent('//layouts/main'); ?>

<?php
	$this->widget('bootstrap.widgets.TbMenu', array(
		'type'=>'tabs',
		'stacked'=>false,
		'items'=>$this->menu,
		'htmlOptions'=>array('class'=>'operations'),
	));
?>
		
<div class="row">
	<div id="sidebar" class="span2">
		
		<?php	
			if (isset($this->sortMenu)):
				$this->beginWidget('zii.widgets.CPortlet', array(
					'title'=>'浏览',
				));
				$this->widget('bootstrap.widgets.TbMenu', array(
					'type'=>'tabs',
					'stacked'=>true,
					'items'=>$this->sortMenu,
					//'htmlOptions'=>array('class'=>'category'),
				));
				$this->endWidget();
			endif;
			if (isset($this->category)):
				$this->beginWidget('zii.widgets.CPortlet', array(
					'title'=>'类别',
				));
				$this->widget('bootstrap.widgets.TbMenu', array(
					'type'=>'tabs',
					'stacked'=>true,
					'items'=>$this->category,
					//'htmlOptions'=>array('class'=>'category'),
				));
				$this->endWidget();
			endif;
		?>
	</div><!-- sidebar -->
	<div id="content" class="span10">
		<?php echo $content; ?>
	</div><!-- content -->
</div>
<?php $this->endContent(); ?>

protected/views/layouts/main.php
<?php /* @var $this Controller */ ?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="language" content="en" />

    <link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->theme->baseUrl; ?>/css/styles.css" />
	
	<title><?php echo CHtml::encode($this->pageTitle); ?></title>

	<?php Yii::app()->bootstrap->register(); ?>
	
</head>

<script type="text/javascript">
        $(document).ready(function () {
            $("ul[id*=searchDropdown] li").click(function () {
				var searchForm=document.getElementById("searchForm");
				var searchInput=document.getElementById("searchInput");
				if ($(this).text() == " 百度")
				{
					searchForm.attributes["search_link"].nodeValue = "http://www.baidu.com/baidu";
					searchInput.name = "word";
					searchInput.placeholder = "百度搜索";
				}
				else if ($(this).text() == " 谷歌")
				{
					searchForm.attributes["search_link"].nodeValue = "https://www.google.com.hk/search";
					searchInput.name = "q";
					searchInput.placeholder = "谷歌搜索";
				}
				else if ($(this).text() == " 淘宝")
				{
					searchForm.attributes["search_link"].nodeValue = "http://s.taobao.com/search";
					searchInput.name = "q";
					searchInput.placeholder = "淘宝搜索";
				}
            });
			$("ul[id*=searchDropdown] li").mouseover(function () {
				$(this).addClass('active'); 
			});
			$("ul[id*=searchDropdown] li").mouseout(function () {
				$(this).removeClass('active'); 
			});
			$("form[id*=searchForm]").submit(function () {
				var searchInput=document.getElementById("searchInput");
				searchInput.value = "";
			});
        });
		
		function searchAction()
		{
			var searchForm=document.getElementById("searchForm");
			var searchInput=document.getElementById("searchInput");
			
			var url = searchForm.attributes["search_link"].nodeValue + '?' + searchInput.name + '=' + searchInput.value;
			window.open(url, '_blank');
			
			return false;
		}
</script>

<body>
<?php 
	$search = 	'<form id="searchForm" class="input-prepend navbar-search" method="get" onsubmit="return searchAction();" search_link="https://www.google.com.hk/search" target="_blank">
					<div class="btn-group">
						<button type="button" class="btn dropdown-toggle" data-toggle="dropdown">
							<span class="caret"></span>
						</button>
						<ul id="searchDropdown" class="dropdown-menu" style="cursor:pointer" >
						  <li name="google" value="https://www.google.com.hk/search"> 谷歌</li>
						  <li name="baidu" value="https://www.baidu.com/search"> 百度</li>
						  <li name="baidu" value="https://www.baidu.com/search"> 淘宝</li>
						</ul>
					</div>
					<input class="span3" id="searchInput" type="text" name="q" placeholder="谷歌搜索" />
					<button class="btn" type="submit" style="display:none">Go!</button>
				</form>';
	
	$this->widget('bootstrap.widgets.TbNavbar',array(
	//'type'=>'inverse',
	'brand'=>'首页',
	'brandUrl'=>array('/Home/'),
    'items'=>array(
        array(
            'class'=>'bootstrap.widgets.TbMenu',
            'items'=>array(
				array('label'=>'发现', 'url'=>array('/Feed/')),
            ),
        ),
		$search,
		array(
            'class'=>'bootstrap.widgets.TbMenu',
            'htmlOptions'=>array('class'=>'pull-right'),
            'items'=>array(
                array('label'=>'注册', 'url'=>array('/site/register'), 'visible'=>Yii::app()->user->isGuest),
				array('label'=>'登陆', 'url'=>array('/site/login'), 'visible'=>Yii::app()->user->isGuest),
				array('label'=>''.Yii::app()->user->name.'', 'url'=>'#', 'visible'=>!Yii::app()->user->isGuest, 'items'=>array(
                    array('label'=>'我的分享', 'url'=>array('/feed/home')),
					array('label'=>'修改密码', 'url'=>array('/account/')),
                    array('label'=>'退出', 'url'=>array('/site/logout')),
                )),
            ),
		),
    ),
)); ?>

<div class="container" id="page">
	<?php /*$this->widget('bootstrap.widgets.TbBreadcrumbs', array(
			 'homeLink'=>CHtml::link('首页',Yii::app()->createUrl('home/')), 
			 'links'=>$this->breadcrumbs,
			));*/ ?>
	<?php echo $content; ?>

	<div class="clear"></div>

	<div id="footer">
		Copyright &copy; <?php echo date('Y'); ?> by 小丑尼莫.<br/>
	</div><!-- footer -->

</div><!-- page -->

</body>
</html>